// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManagement.Infrastructure.MsSql.Data;

#nullable disable

namespace UserManagement.Infrastructure.MsSql.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20250531112606_FakeUserGenerattion")]
    partial class FakeUserGenerattion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("UserManagement.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityTimestamps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastLoginTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityTimestamps = "[]",
                            Email = "admin@example.com",
                            IsActive = true,
                            LastLoginTime = new DateTime(2025, 5, 31, 11, 26, 3, 968, DateTimeKind.Utc).AddTicks(2511),
                            Name = "Admin User",
                            PasswordHash = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8",
                            RegistrationTime = new DateTime(2024, 5, 31, 11, 26, 3, 968, DateTimeKind.Utc).AddTicks(2498)
                        },
                        new
                        {
                            Id = 2,
                            ActivityTimestamps = "[]",
                            Email = "john@example.com",
                            IsActive = true,
                            LastLoginTime = new DateTime(2025, 5, 30, 11, 26, 3, 968, DateTimeKind.Utc).AddTicks(2522),
                            Name = "John Smith",
                            PasswordHash = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8",
                            RegistrationTime = new DateTime(2024, 11, 30, 11, 26, 3, 968, DateTimeKind.Utc).AddTicks(2518)
                        },
                        new
                        {
                            Id = 3,
                            ActivityTimestamps = "[]",
                            Email = "sarah@example.com",
                            IsActive = true,
                            LastLoginTime = new DateTime(2025, 5, 31, 8, 26, 3, 968, DateTimeKind.Utc).AddTicks(2533),
                            Name = "Sarah Johnson",
                            PasswordHash = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8",
                            RegistrationTime = new DateTime(2025, 2, 28, 11, 26, 3, 968, DateTimeKind.Utc).AddTicks(2531)
                        },
                        new
                        {
                            Id = 4,
                            ActivityTimestamps = "[]",
                            Email = "mike@example.com",
                            IsActive = false,
                            LastLoginTime = new DateTime(2025, 5, 21, 11, 26, 3, 968, DateTimeKind.Utc).AddTicks(2540),
                            Name = "Mike Brown",
                            PasswordHash = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8",
                            RegistrationTime = new DateTime(2025, 1, 31, 11, 26, 3, 968, DateTimeKind.Utc).AddTicks(2538)
                        },
                        new
                        {
                            Id = 5,
                            ActivityTimestamps = "[]",
                            Email = "emily@example.com",
                            IsActive = true,
                            LastLoginTime = new DateTime(2025, 5, 31, 6, 26, 3, 968, DateTimeKind.Utc).AddTicks(2546),
                            Name = "Emily Davis",
                            PasswordHash = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8",
                            RegistrationTime = new DateTime(2025, 3, 31, 11, 26, 3, 968, DateTimeKind.Utc).AddTicks(2544)
                        },
                        new
                        {
                            Id = 6,
                            ActivityTimestamps = "[]",
                            Email = "robert@example.com",
                            IsActive = true,
                            LastLoginTime = new DateTime(2025, 5, 29, 11, 26, 3, 968, DateTimeKind.Utc).AddTicks(2559),
                            Name = "Robert Wilson",
                            PasswordHash = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8",
                            RegistrationTime = new DateTime(2024, 12, 31, 11, 26, 3, 968, DateTimeKind.Utc).AddTicks(2557)
                        },
                        new
                        {
                            Id = 7,
                            ActivityTimestamps = "[]",
                            Email = "lisa@example.com",
                            IsActive = false,
                            LastLoginTime = new DateTime(2025, 5, 16, 11, 26, 3, 968, DateTimeKind.Utc).AddTicks(2565),
                            Name = "Lisa Miller",
                            PasswordHash = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8",
                            RegistrationTime = new DateTime(2024, 10, 31, 11, 26, 3, 968, DateTimeKind.Utc).AddTicks(2563)
                        },
                        new
                        {
                            Id = 8,
                            ActivityTimestamps = "[]",
                            Email = "david@example.com",
                            IsActive = true,
                            LastLoginTime = new DateTime(2025, 5, 31, 10, 26, 3, 968, DateTimeKind.Utc).AddTicks(2571),
                            Name = "David Taylor",
                            PasswordHash = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8",
                            RegistrationTime = new DateTime(2025, 4, 30, 11, 26, 3, 968, DateTimeKind.Utc).AddTicks(2569)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
