services:
  - type: web
    name: user-management
    runtime: docker
    env: docker  # OR env: node for native
    plan: free
    region: frankfurt  # Choose closest to your users
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: Data Source=/var/lib/render/app.db
    disk:
      name: data
      mountPath: /var/lib/render
      sizeGB: 1